spring.jpa.show_sql=true
spring.jpa.database=mysql
spring.mvc.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.h2.console.enabled=true
spring.profiles.include=oauth
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1310

logging.level.org.springframework.core.LocalVariableTableParameterNameDiscoverer = error