drop table if exists board CASCADE;
create table board
(
    id bigint generated by default as identity,
    title varchar(200) not null,
    content text not null,
    read_cnt int not null default 0,
    register_id varchar(100) not null,
    register_time datetime null default null,
    update_time datetime null default null,
    primary key(id)
) ;

drop table if exists member CASCADE;
create table member (
    id bigint generated by default as identity,
    email varchar(200) not null,
    pwd varchar(200) not null,
    name varchar(100) not null,
    last_login_time datetime null default null,
    register_time datetime null default null,
    update_time datetime null default null,
    primary key(id)
);
create unique index email on member (email);