drop table if exists board CASCADE;
create table board
(
    id bigint generated by default as identity,
    title varchar(200) not null,
    content text not null,
    read_cnt int not null default 0,
    register_id varchar(100) not null,
    register_email varchar(200) not null,
    register_time datetime null default null,
    update_time datetime null default null,
    primary key(id)
) ;

create table board (
    id bigint auto_increment primary key,
    title varchar(200) not null,
    content text not null,
    read_cnt int not null default 0,
    register_id varchar(100) not null,
    register_email varchar(200) not null,
    register_time datetime null default null,
    update_time datetime null default null);

drop table if exists member CASCADE;
create table member (
    id bigint generated by default as identity,
    email varchar(200) not null,
    pwd varchar(200) not null,
    name varchar(100) not null,
    role varchar(20) not null,
    last_login_time datetime null default null,
    register_time datetime null default null,
    update_time datetime null default null,
    primary key(id)
);

create table member (
    id bigint auto_increment primary key,
    email varchar(200) not null,
    pwd varchar(200) not null,
    name varchar(100) not null,
    role varchar(20) not null,
    last_login_time datetime null default null,
    register_time datetime null default null,
    update_time datetime null default null);
create unique index email on member (email);

create table spring_session (
    primary_id char(36) primary key,
    session_id char(36),
    creation_time bigint,
    last_access_time bigint,
    max_inactive_interval int,
    expiry_time bigint default 60,
    principal_name varchar(100));

create table spring_session_attributes (
    session_primary_id char(36) primary key,
    attribute_name varchar(200),
    attribute_bytes varbinary);